 ---
title: "ggplot2"
output: github_document
---


```{r}
library(tidyverse)
library(patchwork)
library(viridis)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =.6,
  out.width = "90%"
)
```


Loading a dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```



```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = .5)+
  labs(
    title = "Temperation plot",
    x = "Minimun daily temperation",
    y = "Maximum daily temperation",
    caption = "Data from rnoaa pachkage; temperation in 2017"
    )
```


## Scales


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = .5)+
  labs(
    title = "Temperation plot",
    x = "Minimun daily temperation",
    y = "Maximum daily temperation",
    caption = "Data from rnoaa pachkage; temperation in 2017"
    )+
  scale_x_continuous(
    breaks = c(-15,0,15),
    labels = c("-15 C","0","15 C")
  )+scale_y_continuous(
    trans = "sqrt",  ###y = sqrt/log(y)
    position = "right"
  )
```


## COLOR scales

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = .5)+
  labs(
    title = "Temperation plot",
    x = "Minimun daily temperation",
    y = "Maximum daily temperation",
    caption = "Data from rnoaa pachkage; temperation in 2017"
  )+
  scale_color_hue(
    name = "Location",
    h = c(100,300)  #hue: color, tune of color
  )    




```




```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = .5)+
  labs(
    title = "Temperation plot",
    x = "Minimun daily temperation",
    y = "Maximum daily temperation",
    caption = "Data from rnoaa pachkage; temperation in 2017"
  )+
  scale_color_viridis(
     name = "Location",
    discrete = TRUE  #defalt is continuous for vridis
  )


```


## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y= tmax, color = name))+
  geom_point(alpha = .5)+
  labs(
    title = "Temperation plot",
    x = "Minimun daily temperation",
    y = "Maximum daily temperation",
    caption = "Data from rnoaa pachkage; temperation in 2017"
  )+
  scale_color_viridis(
     name = "Location",
    discrete = TRUE)+  #defalt is continuous for vridis
  theme_bw()+  
  ## ggthemes::theme_economist_white()+   # this package provides more themes
  theme(legend.position = "bottom")
  ## Order matters for THEME!!


```


## `data` in geoms

```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki = 
  weather_df %>% 
  filter(name == "Waikiki_HA")


waikiki %>% 
  ggplot(aes(x = date, y=tmax,color = name))+
  geom_point() + 
  geom_line(data = central_park)  ## add an extra dataset

```


## `patchwork`

```{r}
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)+
  theme(legend.position = "none")

ggp_prcp_dens = 
  weather_df %>%
  filter(prcp>0) %>% 
  ggplot(aes(x = prcp,fill = name))+
  geom_density(alpha = .3)+
  theme(legend.position = "none")

ggp_tmax_date = 
  weather_df %>% 
  ggplot(aes(x=date, y = tmax,color=name))+
  geom_point()+
  geom_smooth()+
  theme(legend.position = "none")

(ggp_tmax_tmin+ggp_prcp_dens)/ggp_tmax_date

```

## data manipulation


```{r}
weather_df %>% 
  mutate(
    name = fct_reorder(name, tmax)  ##did two things.
    #1. change character to factor 2. arrange order by average tmax value
  ) %>% 
  ggplot(aes(x = name,y = tmax))+
  geom_boxplot()  ##by alphabetical order
```


## What about tmax and tmin


```{r}
weather_df %>% 
  pivot_longer(tmin:tmax, 
               names_to = "obs", values_to = "temp") %>% 
  ggplot(aes(x=temp, fill = obs))+
  geom_density(alpha = .3)+
  facet_grid(.~name)
```


```{r}
pulse_df = 
  haven::read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    values_to = "bdi",
    names_prefix = "bdi_score_") %>%
  mutate(visit = recode(visit,"bl" = "00m")) 

pulse_df %>% 
  ggplot(aes(x = visit,y = bdi))+
  geom_boxplot()


## helpful for longitutional data analysis
## (want to look at each individual)
pulse_df %>% 
  ggplot(aes(x = visit,y = bdi))+
  geom_point()+
  geom_line(aes(group = id))

```


```{r}
pup_data = 
  read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>% 
  janitor::clean_names()

litter_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names()

pup_litter = left_join(litter_data,pup_data,by = "litter_number") %>% 
  separate(group, into = c("dose","day_of_tx"),3) %>% 
  select(-(3:10)) %>% 
  pivot_longer(3:6,names_to = "event",values_to = "pn_day") 

pup_litter %>% 
  drop_na() %>% 
  mutate(event = fct_reorder(event,pn_day)) %>% 
  ggplot(aes(x = dose, y = pn_day))+
  geom_violin()+
  facet_grid(day_of_tx ~ event)

```




