---
title: "ggplot1"
output: github_document
---


```{r}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp =.6,
  out.width = "90%"
)
```


Loading a dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```


## scatter plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```

## save ggplot

```{r}
ggp_tmax_tmin = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
ggp_tmax_tmin
```


## Let's fancy it up

Add color? lines? others?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)+  # alpha:transparency 
  geom_smooth(se = FALSE) #add smooth lines

## Compare the position of aes()

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + ##
  geom_point(aes(color = name),alpha = .3)+ ##
  geom_smooth(se = FALSE) 

## If we use aes() for all but want to keep one exemption:

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)+  # alpha:transparency 
  geom_smooth(aes(color = NULL),se = FALSE) #add smooth lines


```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)+  # alpha:transparency 
  geom_smooth(se = FALSE)+ #add smooth lines
  facet_grid(. ~ name) # row ~ column, here the . stands for all rows
  
```


Let's make another scatterplot

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp))+ ## size of plot depends on precipitation
  geom_point(alpha = .3)+
  facet_grid(. ~ name)+
  geom_smooth(se=FALSE) ## se:standard error bar

```

Let's use data manipulation as part of this

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax*(9/5)+32,
    tmin = tmin*(9/5)+32
  ) %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_point()
```


## Stacking geoms

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax))+
  geom_bin_2d()
```

Univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x=tmax,fill = name))+
  geom_histogram()+
  facet_grid(.~name)

```

```{r}
weather_df %>% 
  ggplot(aes(x=tmax,fill = name))+
  geom_density(alpha = .3)
```

## Boxplot

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax))+
  geom_boxplot()
```

violin box

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax))+
  geom_violin()
```


What about rigdes


```{r}
weather_df %>% 
  ggplot(aes(x = tmax,y = name))+
  geom_density_ridges(alpha = .6,scale = .8) 
## scale is to make the vertical space between each other larger

```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin,y = tmax,color = name))+
  geom_point(alpha = .3) 
## scale is to make the vertical space between each other larger

```


```{r, fig.width=12}
weather_df %>% 
  ggplot(aes(x = tmin,y = tmax,color = name))+
  geom_point(alpha = .3) 
## scale is to make the vertical space between each other larger

```

